CREATE TABLE PriceHistory(
    IDinShoikee VARCHAR(30) PRIMARY KEY,
    Price MONEY NOT NULL,
    TimeStamp DATE NOT NULL
);

CREATE TABLE ProductInShop(
    IDinShoikee VARCHAR(30) PRIMARY KEY,
    ShopName VARCHAR(100) NOT NULL REFERENCES Shops(ShopName) ON DELETE CASCADE ON UPDATE CASCADE,
    ProductName VARCHAR(300) NOT NULL REFERENCES Products(ProductName) ON DELETE CASCADE ON UPDATE CASCADE,
    IDinShop VARCHAR(30) NOT NULL,
    Price MONEY NOT NULL,
    Quantity INT NOT NULL,
    Rate FLOAT,
    NumofUserRated INT NOT NULL,
);
